# Generated by Django 5.2.1 on 2025-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tipodocumento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educaciondocente',
            name='hoja_de_vida',
        ),
        migrations.AlterField(
            model_name='educaciondocente',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educaciondocente',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='educaciondocente',
            name='nivel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educaciondocente',
            name='titulo_obtenido',
            field=models.CharField(max_length=200),
        ),
    ]
