# Generated by Django 5.2.1 on 2025-09-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_educaciondocente_hoja_de_vida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="departamento_residencia",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="direccion_linea1",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="estado_civil",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.estadocivil",
            ),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="estrato",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.estrato",
            ),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="fecha_nacimiento",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="genero",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.genero"
            ),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="municipio_residencia",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="hojadevidadocente",
            name="pais_residencia",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.pais"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="municipio_identificacion",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_por_municipio_ident",
                to="core.ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="numero_documento",
            field=models.CharField(default="0", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_documento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.tipodocumento",
            ),
        ),
    ]
